### ISSUE TITLE
alternate to DowloadThemAll

### ISSUE THREAD

**Issue by az0** [ZimbiX/echo360-download-tool#1]
In case you want to mention another download method:

Using the LinkGopher extension, you can extract the URLs, then paste them into a file, and then download them using

```
cat urlfile.txt | parallel --gnu "wget {}"
```

**Comment by ZimbiX** [comment]
Ah, right. I tried to keep the barrier to entry as low as possible, but combined with the file-metadata-based renaming you mention in issue #2, this could be a simpler alternative for advanced users.
