### ISSUE TITLE
filenames

### ISSUE THREAD

**Issue by az0** [ZimbiX/echo360-download-tool#2]
My course has 77 videos, so I wish there were a batch way to rename them according to the metadata stored in the MP4.

**Comment by az0** [comment]
``` bash
TMPNAME=/tmp/vidinfo.txt
for f in `ls mediacontent*`; do
    rm -f $TMPNAME
    avconv -loglevel quiet -i "$f" -f ffmetadata $TMPNAME
    title=`cat $TMPNAME  | grep ^title= | cut -c7-`
    # FIXME: avoid overwriting file with the same name
    mv "$f" "$title.mp4"
done
rm -f $TMPNAME
```

**Comment by ZimbiX** [comment]
I don't quite understand how this is useful; for me, the title metadata is the same for each video in the course, e.g., `COS10004_HED_2014_HS2_1297`.

My tool names them by date, e.g.,  `COS10004_HED_2014_HS2_1297 (2014-08-07)`. Hence the downloaded video files should have unique names. If your course has multiple videos per day, perhaps you just need to modify the script to also append the timestamp?

**Comment by ZimbiX** [comment]
If you want to write up instructions for the readme, feel free to submit a pull request =)

**Comment by az0** [comment]
When I downloaded them using wget, I got weird file names like mediacontent?adfadf=blah.  After renaming, I got nice filenames like "Module 1.1." 

If this does not help anyone else, that's fine.
